# Generated by Django 4.2.7 on 2025-08-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
