# Generated by Django 5.2.3 on 2025-08-24 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название курса"),
                ),
                (
                    "preview",
                    models.ImageField(upload_to="course/", verbose_name="Превью курса"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание курса"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название урока"),
                ),
                (
                    "preview",
                    models.ImageField(
                        upload_to="lesson_previews/", verbose_name="Превью"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание урока"),
                ),
                (
                    "video_link",
                    models.URLField(verbose_name="Ссылка на видео"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
