name: Deploy Django App

on:
  push:
    branches: [ main, develop, 32_2, develop_35.2 ]
  pull_request:
    branches: [ develop, develop_35.2 ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django_lms_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run linting
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv,venv,env,__pycache__,.git
        black --check --diff .
        
    - name: Run tests
      env:
        SECRET_KEY: test-secret-key-for-ci
        DEBUG: False
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/django_lms_test
        DB_NAME: django_lms_test
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        python manage.py check
        python manage.py migrate
        python manage.py test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop_35.2' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker images
      run: |
        # Сборка основного образа приложения
        docker build -t studing-place:${{ github.sha }} .
        docker tag studing-place:${{ github.sha }} studing-place:latest
        
        # Сборка образа nginx
        docker build -t studing-place-nginx:${{ github.sha }} ./nginx
        docker tag studing-place-nginx:${{ github.sha }} studing-place-nginx:latest
        
        # Проверка, что образы собрались успешно
        docker images | grep studing-place
    
    - name: Deploy to server with Docker
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/studing_place
          git pull origin develop_35.2
          
          # Остановка старых контейнеров
          docker-compose down || true
          
          # Запуск новых контейнеров
          docker-compose up -d --build
          
          # Очистка неиспользуемых образов
          docker image prune -f
